"""init

Revision ID: 48c2d611e0fd
Revises: None
Create Date: 2017-10-22 18:50:20.111769

"""

# revision identifiers, used by Alembic.
revision = '48c2d611e0fd'
down_revision = None

from alembic import op
import sqlalchemy as sa
import zaih_core


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('unikey', sa.String(length=256), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('realname', sa.String(length=64), nullable=True),
    sa.Column('_avatar', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('date_updated', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_date_updated'), ['date_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_unikey'), ['unikey'], unique=True)

    op.create_table('oauth2_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(length=40), nullable=True),
    sa.Column('session_key', sa.String(length=40), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('scopes', zaih_core.database.JsonString(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    with op.batch_alter_table('oauth2_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth2_token_account_id'), ['account_id'], unique=False)

    op.create_table('wx_authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('openid_type', sa.String(length=64), nullable=False),
    sa.Column('client', sa.String(length=64), server_default=u'LadderTournament', nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date_updated', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'client', 'openid_type')
    )
    with op.batch_alter_table('wx_authentication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wx_authentication_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wx_authentication_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_wx_authentication_date_updated'), ['date_updated'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wx_authentication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wx_authentication_date_updated'))
        batch_op.drop_index(batch_op.f('ix_wx_authentication_date_created'))
        batch_op.drop_index(batch_op.f('ix_wx_authentication_account_id'))

    op.drop_table('wx_authentication')
    with op.batch_alter_table('oauth2_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth2_token_account_id'))

    op.drop_table('oauth2_token')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_unikey'))
        batch_op.drop_index(batch_op.f('ix_account_is_verified'))
        batch_op.drop_index(batch_op.f('ix_account_date_updated'))
        batch_op.drop_index(batch_op.f('ix_account_date_created'))

    op.drop_table('account')
    ### end Alembic commands ###
