swagger: '2.0'
info:
    title: Ladder Tournament App API
    version: '1.0.0'
schemes:
    - http
basePath:
    /app
consumes:
    - application/json
produces:
    - application/json
definitions:
parameters:
securityDefinitions:
    OAuth2:
        type: oauth2
        flow: implicit
        authorizationUrl: http://swagger.io/api/oauth/dialog
        scopes:
            login: 客户端登陆
            panel: 后台登录
paths:
